FROM rust:latest as build

WORKDIR /workspace

ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG BUILD_TARGET=debug
ARG MAKE_TARGET=build

COPY . /workspace

RUN suffix=$(echo ${TARGETPLATFORM} | sed "s/\//-/g") && \
    apt update && \
    apt install -y sudo && \
    ./hack/setup-dev.sh && \
    just ${MAKE_TARGET} && \
    cp target/${BUILD_TARGET}/huber target/${BUILD_TARGET}/huber-${suffix}

FROM scratch
ARG BUILD_TARGET=debug
COPY --from=build /workspace/target/${BUILD_TARGET}/huber-* /target/
