[book]
title = "Huber, simplify GitHub package management"
description = "Install, upgrade and manage released artifacts from GitHub repositories"
authors = ["David Ko"]
language = "en"

[rust]
edition = "2021"

[preprocessor.alerts]

[output.html]
[output.linkcheck]

[output.html.search]
limit-results = 20
