[book]
description = "Install, upgrade and manage GitHub release packages with ease"
authors = ["David Ko"]
language = "en"

[rust]
edition = "2021"

[preprocessor.alerts]

[output.html]
default-theme = "Navy"

[output.linkcheck]

[output.html.search]
limit-results = 20
