# https://github.com/actions/starter-workflows/blob/main/pages/mdbook.yml
name: Deploy docs to Pages

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.44
    steps:
    - uses: actions/checkout@v4

    - name: Install Just
      uses: extractions/setup-just@v2

    - name: Install mdBook
      run: just build-deps

    - name: Enable Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-targets: 'false'

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5

    - name: Build with mdBook
      run: mdbook build ./docs

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs/book

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
